[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Common_PythonDevelopment"
version = "0.0.1"
description = "Python library for 'Common_PythonDevelopment'."
