[build-system]
requires = ["setuptools>=63.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Common_PythonDevelopment"
description = "Python library for 'Common_PythonDevelopment'."
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "__version__.VERSION"}
