<<#
# ----------------------------------------------------------------------
# |
# |  _BuildAndTest_python.template.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-23 10:15:26
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
The following values may be customized by child templates:

  - name: Name of this workflow
  - python_inputs: Additional inputs required by the child template.
  - python_cache_steps: Steps invoked after source is checked out and standard cache content has been restored.
  - python_prologue_steps: Steps invoked after setup and activation but before build and tests.
  - python_epilogue_steps: Steps invoked after build and tests.

#>>

<<% extends "{}/.github/src/_BuildAndTest.template.yaml".format("DEVELOPMENT_ENVIRONMENT_FOUNDATION" | env) %>>

<<% block inputs %>>
      run_PylintVerifier:                   {type: boolean, required: true}
<<% block python_inputs %>><<% endblock %>>
<<% endblock %>>

<<% block cache_steps %>><<% block python_cache_steps %>><<% endblock %>><<% endblock %>>

<<% block prologue_steps %>>
      - name: PylintVerifier
        uses: davidbrownell/v4-Common_PythonDevelopment/.github/actions/pylint_verifier@CI-v1
        if: ${{ inputs.run_PylintVerifier == true || inputs.run_PylintVerifier == 'true' }}
        with:
          os: ${{ inputs.os }}
          configuration: ${{ inputs.configuration }}

          script_extension: ${{ steps.initialize.outputs.script_extension }}
          shell_name: ${{ steps.initialize.outputs.shell_name }}
          working_dir: ${{ steps.initialize.outputs.working_dir }}

          activate_statement: ${{ steps.activate.outputs.activate_statement }}

<<% block python_prologue_steps %>><<% endblock %>>
<<% endblock %>>

<<% block epilogue_steps %>>
<<% block python_epilogue_steps %>><<% endblock %>>
<<% endblock %>>
