# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 09:47:50
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

concurrency: "on_push-${{ github.ref_name }}"

jobs:
  _837fb405-19bf-406f-867a-de0b1975e1ba:
    name: "Validate (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch: ${{ github.ref_name }}

  _d9f0fe2d-2203-4ae4-8cfd-35168e50c372:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _837fb405-19bf-406f-867a-de0b1975e1ba
