# ----------------------------------------------------------------------
# |
# |  main.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-31 14:48:55
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: main
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Common_PythonDevelopment:
    uses: ./.github/workflows/callable_main.yaml
