# ----------------------------------------------------------------------
# |
# |  main.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 14:40:15
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: main
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  _a3fa3751-1863-4670-a89c-3e60a602ac0f:
    name: "[Common_PythonDevelopment]"
    uses: ./.github/workflows/exercise_main.yaml
    with:
      bootstrap_branch_overrides: "v4-Common_PythonDevelopment:${{ github.ref_name }}"
      repo_name: "davidbrownell/v4-Common_PythonDevelopment"
      repo_branch: "${{ github.ref_name }}"

  # ----------------------------------------------------------------------
  _d85d7987-f66b-4730-bfbc-faa03ee06958:
    name: Promote

    needs:
      - _a3fa3751-1863-4670-a89c-3e60a602ac0f

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_create_stable_tag.yaml@CI-v1.2.0
    with:
      branch: ${{ github.ref_name }}
      commit: ${{ github.sha }}
