# ----------------------------------------------------------------------
# |
# |  manual_exercise_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 09:54:47
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate This Repository (and its dependencies)"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _5edf5467-1738-494a-a5a5-dab584b26b41:
    name: "Build and Test All (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/impl_exercise_with_dependencies.yaml@CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}
