# ----------------------------------------------------------------------
# |
# |  callable_PylintVerifier.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-31 14:38:53
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: callable_main

# Sample implementation in the calling workflow:
#
# name: SampleWorkflow
# run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}
#
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#
# jobs:
#   PylintVerifier:
#     strategy:
#       matrix:
#         os:
#           - ubuntu-latest
#           - windows-latest
#
#         configuration:
#           # Enter repository configurations here, or "None" (without quotes) for repositories that aren't configurable
#           - Enter_a_valid_configuration_name_here
#
#     uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_main.yaml@CI-v1.0.0
#     with:
#       os:                                   ${{ matrix.os }}
#       configuration:                        ${{ matrix.configuration }}
#
#       checkout_source:                      true
#
#       run_PylintVerifier:                   true

on:
  workflow_call:
    inputs:
      # ----------------------------------------------------------------------
      # |  Misc
      os:
        type: string
        description: Operating system.
        required: true

      configuration:
        type: string
        description: "Name of the configuration to use when setting up and activating the environment (specify the 'None' string value for repositories that aren't configurable)."
        required: true

      # ----------------------------------------------------------------------
      #  Source Code
      checkout_source:
        type: boolean
        description: "True to checkout the source."
        required: true

      # ----------------------------------------------------------------------
      #  PylintVerifier
      run_PylintVerifier:                   {type: boolean, default: true, required: true}

jobs:
  PylintVerifier:
    runs-on: ${{ inputs.os }}

    env:
      COLUMNS:                                          "200"
      SIMULATE_TERMINAL_CAPABILITIES_SUPPORTS_COLORS:   "1"
      PYTHONIOENCODING:                                 "UTF-8"

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        if: ${{ inputs.checkout_source }}

      - name: "[Impl] Initialize OS-Specific Variables"
        id: initialize
        uses: davidbrownell/v4-Common_Foundation/.github/actions/initialize@CI-v1.0.0
        with:
          os:                               ${{ inputs.os }}

      - name: Setup
        uses: davidbrownell/v4-Common_Foundation/.github/actions/setup@CI-v1.0.0
        with:
          os:                               ${{ inputs.os }}
          configuration:                    ${{ inputs.configuration }}

          local_script_prefix:              ${{ steps.initialize.outputs.local_script_prefix }}
          script_extension:                 ${{ steps.initialize.outputs.script_extension }}
          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          sudo_command:                     ${{ steps.initialize.outputs.sudo_command }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

      - name: Activate
        id: activate
        uses: davidbrownell/v4-Common_Foundation/.github/actions/activate@CI-v1.0.0
        with:
          os:                               ${{ inputs.os }}
          configuration:                    ${{ inputs.configuration }}
          shell_name:                       ${{ steps.initialize.outputs.shell_name }}

      - name: PylintVerifier
        uses: ./.github/actions/pylint_verifier
        if: ${{ inputs.run_PylintVerifier }}
        with:
          os:                               ${{ inputs.os }}
          configuration:                    ${{ inputs.configuration }}

          script_extension:                 ${{ steps.initialize.outputs.script_extension }}
          shell_name:                       ${{ steps.initialize.outputs.shell_name }}
          working_dir:                      ${{ steps.initialize.outputs.working_dir }}

          activate_statement:               ${{ steps.activate.outputs.activate_statement }}
