# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/event_on_push.jinja2.yaml
#     Generated Date:         2022-11-17
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 09:47:50
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main

jobs:
  _837fb405-19bf-406f-867a-de0b1975e1ba:
    name: "Build and Test Dependencies"
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/callable_validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}

  _d9f0fe2d-2203-4ae4-8cfd-35168e50c372:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-v1

    needs:
      - _837fb405-19bf-406f-867a-de0b1975e1ba
