# ----------------------------------------------------------------------
# |
# |  main.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-31 14:48:55
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: main
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ----------------------------------------------------------------------
  BuildAndTest:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        configuration:
          - python310

    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_BuildAndTest.yaml@CI-v1.0.0
    with:
      os:                                   ${{ matrix.os }}
      configuration:                        ${{ matrix.configuration }}

      checkout_source:                      true

      run_Builder:                          true

      # Use the following values to control how different test types are run:
      #
      #   0: Do not run these test types
      #   1: Run these test types without code coverage
      #   2: Run these test types with code coverage
      #   3: Run these test types with and without code coverage

      execute_UnitTests:                    3
      execute_FunctionalTests:              1
      execute_IntegrationTests:             1
      execute_SystemTests:                  1
      execute_LocalEndToEndTests:           1
      execute_EndToEndTests:                0
      execute_BuildVerificationTests:       0
      execute_PerformanceTests:             0

  # ----------------------------------------------------------------------
  PylintVerifier:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        configuration:
          - python310

    uses: ./.github/workflows/callable_PylintVerifier.yaml
    with:
      os:                                   ${{ matrix.os }}
      configuration:                        ${{ matrix.configuration }}

      checkout_source:                      true

      run_PylintVerifier:                   true
